name: txqapp
description: A reactive audiovisual app for meteorological events
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.20.1
  flutter_osc: ^1.1.4
  flutter_mjpeg: ^1.2.1

flutter:
  uses-material-design: true
